-- Full schema from the brief
create extension if not exists pgcrypto;

create table site_settings ( id uuid primary key default gen_random_uuid(), whatsapp_number text not null default '', whatsapp_message_en text default '', whatsapp_message_fr text default '', hero_eyebrow_en text, hero_eyebrow_fr text, hero_title_en text, hero_title_fr text, hero_subtitle_en text, hero_subtitle_fr text, hero_timezone text not null default 'Africa/Tunis', logo_url text, updated_at timestamptz not null default now() );
create table projects ( id uuid primary key default gen_random_uuid(), title_en text not null, title_fr text not null, description_en text, description_fr text, website_url text, cover_image_url text, images text[] not null default '{}', is_published boolean not null default true, order_index int not null default 0, created_at timestamptz not null default now(), constraint max_eight_images check (array_length(images, 1) is null or array_length(images, 1) <= 8) );
create table pricing_packages ( id uuid primary key default gen_random_uuid(), name_en text not null, name_fr text not null, price numeric not null, currency text not null default 'DT', billing_suffix_en text default '', billing_suffix_fr text default '', ideal_for_en text, ideal_for_fr text, features_en text[] not null default '{}', features_fr text[] not null default '{}', delivery_en text, delivery_fr text, is_featured boolean not null default false, order_index int not null default 0, created_at timestamptz not null default now() );
create table team_members ( id uuid primary key default gen_random_uuid(), name text not null, title_en text, title_fr text, bio_en text, bio_fr text, photo_url text, order_index int not null default 0, created_at timestamptz not null default now() );

alter table site_settings enable row level security;
alter table projects enable row level security;
alter table pricing_packages enable row level security;
alter table team_members enable row level security;

create policy "Public read" on site_settings for select using (true);
create policy "Public read" on projects for select using (true);
create policy "Public read" on pricing_packages for select using (true);
create policy "Public read" on team_members for select using (true);

create policy "Admin write" on site_settings for all using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');
create policy "Admin write" on projects for all using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');
create policy "Admin write" on pricing_packages for all using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');
create policy "Admin write" on team_members for all using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');

insert into storage.buckets (id, name, public) values ('project-images', 'project-images', true);
insert into storage.buckets (id, name, public) values ('team-photos', 'team-photos', true);
insert into storage.buckets (id, name, public) values ('site-assets', 'site-assets', true);

create policy "Public read" on storage.objects for select using (bucket_id in ('project-images','team-photos','site-assets'));
create policy "Admin upload" on storage.objects for insert with check (auth.role() = 'authenticated' and bucket_id in ('project-images','team-photos','site-assets'));
create policy "Admin update" on storage.objects for update using (auth.role() = 'authenticated' and bucket_id in ('project-images','team-photos','site-assets'));
create policy "Admin delete" on storage.objects for delete using (auth.role() = 'authenticated' and bucket_id in ('project-images','team-photos','site-assets'));

insert into site_settings (whatsapp_number, whatsapp_message_en, whatsapp_message_fr, hero_eyebrow_en, hero_eyebrow_fr, hero_title_en, hero_title_fr, hero_subtitle_en, hero_subtitle_fr, hero_timezone) values ('21600000000', 'Hi! I'd like to learn more about your web development packages.', 'Bonjour ! J'aimerais en savoir plus sur vos forfaits de développement web.', 'Web Design & Development Studio', 'Studio de Conception & Développement Web', 'We Build Digital Experiences That Convert', 'Nous Créons des Expériences Digitales Qui Convertissent', 'ROWAAD is a web design & development studio helping ambitious businesses launch fast, beautiful, high-performing websites.', 'ROWAAD est un studio de conception et développement web qui aide les entreprises ambitieuses à lancer des sites rapides, beaux et performants.', 'Africa/Tunis');

insert into pricing_packages (name_en, name_fr, price, currency, billing_suffix_en, billing_suffix_fr, ideal_for_en, ideal_for_fr, features_en, features_fr, delivery_en, delivery_fr, is_featured, order_index) values ('Landing Page', 'Page Vitrine', 600, 'DT', '', '', 'Freelancers, personal brands, and single-service businesses that need a fast, professional presence online.', 'Freelances, marques personnelles et entreprises mono-service ayant besoin d''une présence professionnelle rapide en ligne.', ARRAY['Single-page responsive website (mobile, tablet, desktop)','Custom design aligned to your brand','Contact form','Basic SEO setup (titles, meta descriptions, sitemap)','Free SSL certificate (HTTPS)','1 round of revisions'], ARRAY['Site responsive une page (mobile, tablette, ordinateur)','Design personnalisé aligné à votre marque','Formulaire de contact','Configuration SEO de base (titres, meta descriptions, sitemap)','Certificat SSL gratuit (HTTPS)','1 tour de révisions'], '5–7 business days', '5 à 7 jours ouvrables', false, 1);
insert into pricing_packages (name_en, name_fr, price, currency, billing_suffix_en, billing_suffix_fr, ideal_for_en, ideal_for_fr, features_en, features_fr, delivery_en, delivery_fr, is_featured, order_index) values ('Website Redesign', 'Refonte de Site Web', 1200, 'DT', '', '', 'Businesses whose current site looks outdated or isn''t converting visitors into clients.', 'Entreprises dont le site actuel semble dépassé ou ne convertit pas les visiteurs en clients.', ARRAY['Full visual and structural redesign of your existing site','Content migrated from your current site','Improved page load speed','Mobile-responsive redesign','Refreshed SEO structure','2 rounds of revisions'], ARRAY['Refonte visuelle et structurelle complète de votre site existant','Migration du contenu depuis votre site actuel','Amélioration de la vitesse de chargement','Refonte responsive mobile','Structure SEO actualisée','2 tours de révisions'], '2–3 weeks', '2 à 3 semaines', false, 2);
insert into pricing_packages (name_en, name_fr, price, currency, billing_suffix_en, billing_suffix_fr, ideal_for_en, ideal_for_fr, features_en, features_fr, delivery_en, delivery_fr, is_featured, order_index) values ('Business Website', 'Site Web Professionnel', 1800, 'DT', '', '', 'SMEs and professional services building a complete online presence.', 'PME et services professionnels souhaitant construire une présence en ligne complète.', ARRAY['5–8 pages (Home, About, Services, Gallery, Contact, etc.)','Content management system — update text and images yourself','Mobile-responsive design','Contact form with Google Maps integration','Basic SEO setup','Social media integration','Free SSL certificate','Short training session on managing your own content','2 rounds of revisions'], ARRAY['5 à 8 pages (Accueil, À propos, Services, Galerie, Contact, etc.)','Système de gestion de contenu — modifiez textes et images vous-même','Design responsive mobile','Formulaire de contact avec intégration Google Maps','Configuration SEO de base','Intégration des réseaux sociaux','Certificat SSL gratuit','Courte session de formation pour gérer votre contenu','2 tours de révisions'], '3–4 weeks', '3 à 4 semaines', true, 3);
insert into pricing_packages (name_en, name_fr, price, currency, billing_suffix_en, billing_suffix_fr, ideal_for_en, ideal_for_fr, features_en, features_fr, delivery_en, delivery_fr, is_featured, order_index) values ('E-Commerce Website', 'Site E-Commerce', 4500, 'DT', '', '', 'Businesses ready to sell online.', 'Entreprises prêtes à vendre en ligne.', ARRAY['Full online store with product catalog (up to 100 products)','Shopping cart and secure checkout','Local payment gateway integration','Cash-on-delivery option','Order and inventory management dashboard','Mobile-responsive design','Basic SEO setup','Free SSL certificate','Admin dashboard training session','2 rounds of revisions'], ARRAY['Boutique en ligne complète avec catalogue produits (jusqu''à 100 produits)','Panier d''achat et paiement sécurisé','Intégration de passerelle de paiement locale','Option paiement à la livraison','Tableau de bord de gestion des commandes et des stocks','Design responsive mobile','Configuration SEO de base','Certificat SSL gratuit','Session de formation au tableau de bord admin','2 tours de révisions'], '5–7 weeks', '5 à 7 semaines', false, 4);
insert into pricing_packages (name_en, name_fr, price, currency, billing_suffix_en, billing_suffix_fr, ideal_for_en, ideal_for_fr, features_en, features_fr, delivery_en, delivery_fr, is_featured, order_index) values ('Custom Web Application', 'Application Web Sur Mesure', 6500, 'DT', '', '', 'Businesses that need a booking system, internal tool, or custom dashboard built around their workflow.', 'Entreprises ayant besoin d''un système de réservation, d''un outil interne ou d''un tableau de bord sur mesure.', ARRAY['Custom-built application designed around your process','User login and authentication','Admin control panel','Database-driven, built to scale with your business','Automated email notifications','Mobile-responsive interface','30 days of post-launch bug-fix support'], ARRAY['Application sur mesure conçue autour de votre processus','Connexion et authentification utilisateur','Panneau de contrôle admin','Basée sur une base de données, conçue pour évoluer avec votre entreprise','Notifications automatiques par email','Interface responsive mobile','30 jours de support post-lancement pour la correction de bugs'], '6–8 weeks', '6 à 8 semaines', false, 5);
insert into pricing_packages (name_en, name_fr, price, currency, billing_suffix_en, billing_suffix_fr, ideal_for_en, ideal_for_fr, features_en, features_fr, delivery_en, delivery_fr, is_featured, order_index) values ('Advanced Web Platform', 'Plateforme Web Avancée', 15000, 'DT', '', '', 'Businesses that need a full multi-feature platform, not just a website.', 'Entreprises ayant besoin d''une plateforme complète multi-fonctionnalités, pas seulement d''un site web.', ARRAY['Multiple user roles and permission levels','Multiple integrated modules (booking, payments, reporting, and more)','Payment processing integration','Admin analytics dashboard','Third-party API integrations','Built on scalable architecture to grow with your business','Scheduled milestones with progress updates throughout the build','60 days of post-launch support'], ARRAY['Plusieurs rôles utilisateurs et niveaux de permissions','Modules intégrés multiples (réservation, paiements, rapports, et plus)','Intégration du traitement des paiements','Tableau de bord analytique admin','Intégrations d''API tierces','Architecture évolutive conçue pour accompagner votre croissance','Jalons planifiés avec mises à jour régulières durant le développement','60 jours de support post-lancement'], '10–14 weeks', '10 à 14 semaines', false, 6);
insert into pricing_packages (name_en, name_fr, price, currency, billing_suffix_en, billing_suffix_fr, ideal_for_en, ideal_for_fr, features_en, features_fr, delivery_en, delivery_fr, is_featured, order_index) values ('Monthly Maintenance Plan', 'Plan de Maintenance Mensuel', 160, 'DT', ' / month', ' / mois', 'Any client who wants peace of mind after launch.', 'Tout client souhaitant la tranquillité d''esprit après le lancement.', ARRAY['Security updates and regular backups','Uptime monitoring','Up to 2 hours of content updates per month','Priority support','Monthly performance report'], ARRAY['Mises à jour de sécurité et sauvegardes régulières','Surveillance de la disponibilité (uptime)','Jusqu''à 2 heures de mises à jour de contenu par mois','Support prioritaire','Rapport de performance mensuel'], 'Ongoing', 'Continu', false, 7);
